### ISSUE TITLE
Problem during compile

### ISSUE THREAD

**Issue by amlarraz** [splashblot/cvjena-darknet#2]
Hi! I tried to do the "make" with:

GPU=1
CUDNN=1
OPENCV=1

and give me the following error (i paste all the compilation messages for more information):

mkdir -p obj
mkdir -p results
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DOPENCV -DGPU -DCUDNN -c ./src/gemm.c -o obj/gemm.o
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DOPENCV -DGPU -DCUDNN -c ./src/utils.c -o obj/utils.o
./src/utils.c: In function ‘fgetl’:
./src/utils.c:284:9: warning: ignoring return value of ‘fgets’, declared with attribute warn_unused_result [-Wunused-result]
         fgets(&line[curr], readsize, fp);
         ^
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DOPENCV -DGPU -DCUDNN -c ./src/cuda.c -o obj/cuda.o
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DOPENCV -DGPU -DCUDNN -c ./src/deconvolutional_layer.c -o obj/deconvolutional_layer.o
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DOPENCV -DGPU -DCUDNN -c ./src/convolutional_layer.c -o obj/convolutional_layer.o
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DOPENCV -DGPU -DCUDNN -c ./src/list.c -o obj/list.o
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DOPENCV -DGPU -DCUDNN -c ./src/image.c -o obj/image.o
./src/image.c: In function ‘save_image_jpg’:
./src/image.c:410:13: warning: variable ‘params’ set but not used [-Wunused-but-set-variable]
         int params[3];
             ^
./src/image.c: In function ‘test_resize’:
./src/image.c:922:5: warning: implicit declaration of function ‘shortcut_gpu’ [-Wimplicit-function-declaration]
     shortcut_gpu(3, r.w, r.h, 1, r_gpu, black.w, black.h, 3, black_gpu);
     ^
./src/image.c: In function ‘load_image_cv’:
./src/image.c:1025:9: warning: ignoring return value of ‘system’, declared with attribute warn_unused_result [-Wunused-result]
         system(buff);
         ^
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DOPENCV -DGPU -DCUDNN -c ./src/activations.c -o obj/activations.o
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DOPENCV -DGPU -DCUDNN -c ./src/im2col.c -o obj/im2col.o
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DOPENCV -DGPU -DCUDNN -c ./src/col2im.c -o obj/col2im.o
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DOPENCV -DGPU -DCUDNN -c ./src/blas.c -o obj/blas.o
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DOPENCV -DGPU -DCUDNN -c ./src/crop_layer.c -o obj/crop_layer.o
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DOPENCV -DGPU -DCUDNN -c ./src/dropout_layer.c -o obj/dropout_layer.o
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DOPENCV -DGPU -DCUDNN -c ./src/maxpool_layer.c -o obj/maxpool_layer.o
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DOPENCV -DGPU -DCUDNN -c ./src/softmax_layer.c -o obj/softmax_layer.o
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DOPENCV -DGPU -DCUDNN -c ./src/data.c -o obj/data.o
./src/data.c: In function ‘load_cifar10_data’:
./src/data.c:843:9: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
         fread(bytes, 1, 3073, fp);
         ^
./src/data.c: In function ‘load_all_cifar10’:
./src/data.c:907:13: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
             fread(bytes, 1, 3073, fp);
             ^
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DOPENCV -DGPU -DCUDNN -c ./src/matrix.c -o obj/matrix.o
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DOPENCV -DGPU -DCUDNN -c ./src/network.c -o obj/network.o
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DOPENCV -DGPU -DCUDNN -c ./src/connected_layer.c -o obj/connected_layer.o
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DOPENCV -DGPU -DCUDNN -c ./src/cost_layer.c -o obj/cost_layer.o
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DOPENCV -DGPU -DCUDNN -c ./src/parser.c -o obj/parser.o
./src/parser.c: In function ‘load_connected_weights’:
./src/parser.c:985:5: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
     fread(l.biases, sizeof(float), l.outputs, fp);
     ^
./src/parser.c:986:5: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
     fread(l.weights, sizeof(float), l.outputs_l.inputs, fp);
     ^
./src/parser.c:993:9: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
         fread(l.scales, sizeof(float), l.outputs, fp);
         ^
./src/parser.c:994:9: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
         fread(l.rolling_mean, sizeof(float), l.outputs, fp);
         ^
./src/parser.c:995:9: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
         fread(l.rolling_variance, sizeof(float), l.outputs, fp);
         ^
./src/parser.c: In function ‘load_batchnorm_weights’:
./src/parser.c:1009:5: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
     fread(l.scales, sizeof(float), l.c, fp);
     ^
./src/parser.c:1010:5: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
     fread(l.rolling_mean, sizeof(float), l.c, fp);
     ^
./src/parser.c:1011:5: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
     fread(l.rolling_variance, sizeof(float), l.c, fp);
     ^
./src/parser.c: In function ‘load_convolutional_weights_binary’:
./src/parser.c:1021:5: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
     fread(l.biases, sizeof(float), l.n, fp);
     ^
./src/parser.c:1023:9: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
         fread(l.scales, sizeof(float), l.n, fp);
         ^
./src/parser.c:1024:9: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
         fread(l.rolling_mean, sizeof(float), l.n, fp);
         ^
./src/parser.c:1025:9: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
         fread(l.rolling_variance, sizeof(float), l.n, fp);
         ^
./src/parser.c:1031:9: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
         fread(&mean, sizeof(float), 1, fp);
         ^
./src/parser.c:1035:13: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
             fread(&c, sizeof(char), 1, fp);
             ^
./src/parser.c: In function ‘load_convolutional_weights’:
./src/parser.c:1056:5: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
     fread(l.biases, sizeof(float), l.n, fp);
     ^
./src/parser.c:1058:9: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
         fread(l.scales, sizeof(float), l.n, fp);
         ^
./src/parser.c:1059:9: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
         fread(l.rolling_mean, sizeof(float), l.n, fp);
         ^
./src/parser.c:1060:9: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
         fread(l.rolling_variance, sizeof(float), l.n, fp);
         ^
./src/parser.c:1062:5: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
     fread(l.filters, sizeof(float), num, fp);
     ^
./src/parser.c: In function ‘load_weights_upto’:
./src/parser.c:1085:5: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
     fread(&major, sizeof(int), 1, fp);
     ^
./src/parser.c:1086:5: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
     fread(&minor, sizeof(int), 1, fp);
     ^
./src/parser.c:1087:5: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
     fread(&revision, sizeof(int), 1, fp);
     ^
./src/parser.c:1088:5: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
     fread(net->seen, sizeof(int), 1, fp);
     ^
./src/parser.c:1100:13: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
             fread(l.biases, sizeof(float), l.n, fp);
             ^
./src/parser.c:1101:13: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
             fread(l.filters, sizeof(float), num, fp);
             ^
./src/parser.c:1135:13: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
             fread(l.biases, sizeof(float), l.outputs, fp);
             ^
./src/parser.c:1136:13: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
             fread(l.filters, sizeof(float), size, fp);
             ^
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DOPENCV -DGPU -DCUDNN -c ./src/option_list.c -o obj/option_list.o
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DOPENCV -DGPU -DCUDNN -c ./src/darknet.c -o obj/darknet.o
./src/darknet.c: In function ‘change_rate’:
./src/darknet.c:37:5: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
     fread(&rate, sizeof(float), 1, fp);
     ^
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DOPENCV -DGPU -DCUDNN -c ./src/detection_layer.c -o obj/detection_layer.o
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DOPENCV -DGPU -DCUDNN -c ./src/imagenet.c -o obj/imagenet.o
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DOPENCV -DGPU -DCUDNN -c ./src/captcha.c -o obj/captcha.o
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DOPENCV -DGPU -DCUDNN -c ./src/route_layer.c -o obj/route_layer.o
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DOPENCV -DGPU -DCUDNN -c ./src/writing.c -o obj/writing.o
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DOPENCV -DGPU -DCUDNN -c ./src/box.c -o obj/box.o
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DOPENCV -DGPU -DCUDNN -c ./src/nightmare.c -o obj/nightmare.o
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DOPENCV -DGPU -DCUDNN -c ./src/normalization_layer.c -o obj/normalization_layer.o
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DOPENCV -DGPU -DCUDNN -c ./src/avgpool_layer.c -o obj/avgpool_layer.o
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DOPENCV -DGPU -DCUDNN -c ./src/coco.c -o obj/coco.o
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DOPENCV -DGPU -DCUDNN -c ./src/dice.c -o obj/dice.o
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DOPENCV -DGPU -DCUDNN -c ./src/yolo.c -o obj/yolo.o
./src/yolo.c: In function ‘test_yolo’:
./src/yolo.c:462:39: warning: format ‘%s’ expects argument of type ‘char *’, but argument 12 has type ‘double’ [-Wformat=]
                     fprintf(fout_box, "%s,%.2f,%s,%s,%s,%d,%d,%d,%d,%s\n", inpu
                                       ^
./src/yolo.c:462:39: warning: too many arguments for format [-Wformat-extra-args]
./src/yolo.c:451:17: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
                 fread(encodeBuf, fsize, 1, fp_jpeg_version);
                 ^
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DOPENCV -DGPU -DCUDNN -c ./src/layer.c -o obj/layer.o
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DOPENCV -DGPU -DCUDNN -c ./src/compare.c -o obj/compare.o
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DOPENCV -DGPU -DCUDNN -c ./src/classifier.c -o obj/classifier.o
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DOPENCV -DGPU -DCUDNN -c ./src/local_layer.c -o obj/local_layer.o
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DOPENCV -DGPU -DCUDNN -c ./src/swag.c -o obj/swag.o
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DOPENCV -DGPU -DCUDNN -c ./src/shortcut_layer.c -o obj/shortcut_layer.o
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DOPENCV -DGPU -DCUDNN -c ./src/activation_layer.c -o obj/activation_layer.o
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DOPENCV -DGPU -DCUDNN -c ./src/rnn_layer.c -o obj/rnn_layer.o
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DOPENCV -DGPU -DCUDNN -c ./src/gru_layer.c -o obj/gru_layer.o
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DOPENCV -DGPU -DCUDNN -c ./src/rnn.c -o obj/rnn.o
./src/rnn.c: In function ‘train_char_rnn’:
./src/rnn.c:146:9: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
         fread(text, 1, size, fp);
         ^
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DOPENCV -DGPU -DCUDNN -c ./src/rnn_vid.c -o obj/rnn_vid.o
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DOPENCV -DGPU -DCUDNN -c ./src/crnn_layer.c -o obj/crnn_layer.o
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DOPENCV -DGPU -DCUDNN -c ./src/demo.c -o obj/demo.o
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DOPENCV -DGPU -DCUDNN -c ./src/tag.c -o obj/tag.o
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DOPENCV -DGPU -DCUDNN -c ./src/cifar.c -o obj/cifar.o
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DOPENCV -DGPU -DCUDNN -c ./src/go.c -o obj/go.o
./src/go.c: In function ‘engine_go’:
./src/go.c:451:9: warning: ignoring return value of ‘scanf’, declared with attribute warn_unused_result [-Wunused-result]
         scanf("%s", buff);
         ^
./src/go.c:465:13: warning: ignoring return value of ‘scanf’, declared with attribute warn_unused_result [-Wunused-result]
             scanf("%s", comm);
             ^
./src/go.c:486:13: warning: ignoring return value of ‘scanf’, declared with attribute warn_unused_result [-Wunused-result]
             scanf("%d", &boardsize);
             ^
./src/go.c:499:13: warning: ignoring return value of ‘scanf’, declared with attribute warn_unused_result [-Wunused-result]
             scanf("%f", &komi);
             ^
./src/go.c:503:13: warning: ignoring return value of ‘scanf’, declared with attribute warn_unused_result [-Wunused-result]
             scanf("%s ", color);
             ^
./src/go.c:535:13: warning: ignoring return value of ‘scanf’, declared with attribute warn_unused_result [-Wunused-result]
             scanf("%s", color);
             ^
./src/go.c:562:13: warning: ignoring return value of ‘scanf’, declared with attribute warn_unused_result [-Wunused-result]
             scanf("%s", type);
             ^
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DOPENCV -DGPU -DCUDNN -c ./src/batchnorm_layer.c -o obj/batchnorm_layer.o
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DOPENCV -DGPU -DCUDNN -c ./src/art.c -o obj/art.o
gcc  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DOPENCV -DGPU -DCUDNN -c ./src/detection_conversion.c -o obj/detection_conversion.o
nvcc --gpu-architecture=compute_61 --gpu-code=compute_61  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda/include/ -DCUDNN  --compiler-options "-Wall -Wfatal-errors  -Ofast -DOPENCV -DGPU -DCUDNN" -c ./src/convolutional_kernels.cu -o obj/convolutional_kernels.o
nvcc --gpu-architecture=compute_61 --gpu-code=compute_61  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda/include/ -DCUDNN  --compiler-options "-Wall -Wfatal-errors  -Ofast -DOPENCV -DGPU -DCUDNN" -c ./src/deconvolutional_kernels.cu -o obj/deconvolutional_kernels.o
nvcc --gpu-architecture=compute_61 --gpu-code=compute_61  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda/include/ -DCUDNN  --compiler-options "-Wall -Wfatal-errors  -Ofast -DOPENCV -DGPU -DCUDNN" -c ./src/activation_kernels.cu -o obj/activation_kernels.o
nvcc --gpu-architecture=compute_61 --gpu-code=compute_61  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda/include/ -DCUDNN  --compiler-options "-Wall -Wfatal-errors  -Ofast -DOPENCV -DGPU -DCUDNN" -c ./src/im2col_kernels.cu -o obj/im2col_kernels.o
nvcc --gpu-architecture=compute_61 --gpu-code=compute_61  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda/include/ -DCUDNN  --compiler-options "-Wall -Wfatal-errors  -Ofast -DOPENCV -DGPU -DCUDNN" -c ./src/col2im_kernels.cu -o obj/col2im_kernels.o
nvcc --gpu-architecture=compute_61 --gpu-code=compute_61  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda/include/ -DCUDNN  --compiler-options "-Wall -Wfatal-errors  -Ofast -DOPENCV -DGPU -DCUDNN" -c ./src/blas_kernels.cu -o obj/blas_kernels.o
nvcc --gpu-architecture=compute_61 --gpu-code=compute_61  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda/include/ -DCUDNN  --compiler-options "-Wall -Wfatal-errors  -Ofast -DOPENCV -DGPU -DCUDNN" -c ./src/crop_layer_kernels.cu -o obj/crop_layer_kernels.o
nvcc --gpu-architecture=compute_61 --gpu-code=compute_61  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda/include/ -DCUDNN  --compiler-options "-Wall -Wfatal-errors  -Ofast -DOPENCV -DGPU -DCUDNN" -c ./src/dropout_layer_kernels.cu -o obj/dropout_layer_kernels.o
nvcc --gpu-architecture=compute_61 --gpu-code=compute_61  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda/include/ -DCUDNN  --compiler-options "-Wall -Wfatal-errors  -Ofast -DOPENCV -DGPU -DCUDNN" -c ./src/maxpool_layer_kernels.cu -o obj/maxpool_layer_kernels.o
nvcc --gpu-architecture=compute_61 --gpu-code=compute_61  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda/include/ -DCUDNN  --compiler-options "-Wall -Wfatal-errors  -Ofast -DOPENCV -DGPU -DCUDNN" -c ./src/softmax_layer_kernels.cu -o obj/softmax_layer_kernels.o
nvcc --gpu-architecture=compute_61 --gpu-code=compute_61  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda/include/ -DCUDNN  --compiler-options "-Wall -Wfatal-errors  -Ofast -DOPENCV -DGPU -DCUDNN" -c ./src/network_kernels.cu -o obj/network_kernels.o
nvcc --gpu-architecture=compute_61 --gpu-code=compute_61  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda/include/ -DCUDNN  --compiler-options "-Wall -Wfatal-errors  -Ofast -DOPENCV -DGPU -DCUDNN" -c ./src/avgpool_layer_kernels.cu -o obj/avgpool_layer_kernels.o
nvcc --gpu-architecture=compute_61 --gpu-code=compute_61  -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda/include/ -DCUDNN  --compiler-options "-Wall -Wfatal-errors  -Ofast -DOPENCV -DGPU -DCUDNN" -c ./src/yolo_kernels.cu -o obj/yolo_kernels.o
./src/yolo_kernels.cu(82): error: argument of type "char *_" is incompatible with parameter of type "image *"

./src/yolo_kernels.cu(82): error: argument of type "image _" is incompatible with parameter of type "char *_"

./src/yolo_kernels.cu(82): error: argument of type "int" is incompatible with parameter of type "image *"

./src/yolo_kernels.cu(82): error: too few arguments in function call

4 errors detected in the compilation of "/tmp/tmpxft_0000257d_00000000-7_yolo_kernels.cpp1.ii".
Makefile:68: fallo en las instrucciones para el objetivo 'obj/yolo_kernels.o'
make: **\* [obj/yolo_kernels.o] Error 2

**Comment by jjmata** [comment]
I never compile with CUDNN, so I will have to test that ... can you try to build the original `cvjena` repo (without my changes) and see if it works?  I ask because I never touched `yolo_kernels.cu` and it might be a problem upstream.

PS.  This was a problem even with just `GPU=1`, not even `CUDNN` ...

**Comment by jjmata** [comment]
I just spent some time on this, and it happens to be a [known issue](https://groups.google.com/forum/#!topic/darknet/AfZcD-C6yXY).

The solution for now is to compile with no OPENCV, which works well for your use case -but not mine, since I need the `.jpg`\- output.

**Comment by jjmata** [comment]
Fixed [here](https://github.com/splashblot/cvjena-darknet/commit/088c499fddf9011c70c433e62d26cbe570c8ee7c), give it a shot and let me know, @amlarraz.

**Comment by amlarraz** [comment]
Ok!! everything perfect! with your changes and some little openCV libraries-problems fixed, all working perfectly! thanks!
